#![allow(unused)]
fn main() {
    // 12 words generated with randomwordgenerator.com + 2 generated by me (apple and orange)
    let words = vec![
        "feel",
        "grind",
        "ring",
        "promote",
        "holiday",
        "federation",
        "bedroom",
        "personal",
        "house",
        "state",
        "report",
        "job",
        "apple",
        "orange",
    ];

    let vowels = vec!['a', 'e', 'i', 'o', 'u'];

    let mut pig_latin_words: Vec<String> = vec![];

    for word in &words {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            let mut pig_latin_word = String::new();
            for char in chars {
                pig_latin_word.push(char);
            }
            if vowels.contains(&first) {
                pig_latin_word = format!("{}-hay", pig_latin_word);
            } else {
                pig_latin_word = format!("{}-{}ay", pig_latin_word, first);
            }
            pig_latin_words.push(pig_latin_word);
        }
    }

    println!("{:?}", words);
    println!("{:?}", pig_latin_words);
}
